name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Base
          user: goodeath
          template: classic
          base: header, activity, repositories
          config_timezone: America/Sao_Paulo

          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15

          plugin_repositories: yes
          plugin_repositories_pinned: yes
          plugin_repositories_featured: yes
          plugin_repositories_order: featured
