name: Generate GitHub Readme Stats

on:
  schedule:
    - cron: "0 3 * * *" # daily
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clone github-readme-stats
        run: |
          git clone https://github.com/anuraghazra/github-readme-stats.git

      - name: Install dependencies
        run: |
          cd github-readme-stats
          npm install

      - name: Generate stats
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          cd github-readme-stats

          node src/renderStats.js \
            --username goodeath \
            --theme dark \
            --show_icons true \
            > ../stats/github-stats.svg

          node src/renderTopLanguages.js \
            --username goodeath \
            --theme dark \
            --layout compact \
            > ../stats/github-langs.svg

          node src/renderRepoCard.js \
            --username goodeath \
            --repo assembly-lcd \
            --theme dark \
            > ../stats/repo-assembly-lcd.svg


          node src/renderRepoCard.js \
            --username goodeath \
            --repo tictactoe-multiplayer \
            --theme dark \
            > ../stats/repo-tictactoe-multiplayer.svg


      - name: Commit stats
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add stats/*.svg
          git commit -m "Update GitHub stats" || echo "No changes"
          git push

